BEGIN;

-- Configuracion logica por empresa legal. La ruta y el token NO se guardan
-- en PostgreSQL: credencial_clave solo identifica las variables de entorno
-- NUBEFACT_<CREDENCIAL_CLAVE>_API_URL y NUBEFACT_<CREDENCIAL_CLAVE>_TOKEN.
CREATE TABLE IF NOT EXISTS fg_empresa_facturador (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_key VARCHAR NOT NULL,
    proveedor VARCHAR(30) NOT NULL DEFAULT 'NUBEFACT',
    entorno VARCHAR(20) NOT NULL DEFAULT 'DEMO',
    credencial_clave VARCHAR(80) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion TIMESTAMP WITHOUT TIME ZONE NULL,
    CONSTRAINT fk_fg_empresa_facturador_empresa
        FOREIGN KEY (empresa_key) REFERENCES fg_empresa(key)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT ck_fg_empresa_facturador_proveedor
        CHECK (proveedor IN ('NUBEFACT')),
    CONSTRAINT ck_fg_empresa_facturador_entorno
        CHECK (entorno IN ('DEMO', 'PRODUCCION')),
    CONSTRAINT ck_fg_empresa_facturador_credencial
        CHECK (credencial_clave ~ '^[A-Z0-9_]+$'),
    CONSTRAINT uq_fg_empresa_facturador
        UNIQUE (empresa_key, proveedor, entorno),
    CONSTRAINT uq_fg_empresa_facturador_credencial
        UNIQUE (proveedor, entorno, credencial_clave)
);

CREATE INDEX IF NOT EXISTS idx_fg_empresa_facturador_activo
    ON fg_empresa_facturador (empresa_key, proveedor, entorno, activo);

-- Crea solo referencias logicas DEMO; no activa llamadas ni almacena secretos.
INSERT INTO fg_empresa_facturador (
    empresa_key, proveedor, entorno, credencial_clave, activo
)
SELECT e.key,
       'NUBEFACT',
       'DEMO',
       UPPER(REGEXP_REPLACE(REGEXP_REPLACE(BTRIM(e.key), '[^A-Za-z0-9]+', '_', 'g'), '^_|_$', '', 'g')),
       TRUE
FROM fg_empresa e
WHERE e.activo = TRUE
  AND BTRIM(e.key) <> ''
ON CONFLICT (empresa_key, proveedor, entorno) DO NOTHING;

-- Snapshot del emisor: una factura conserva la empresa/RUC que la emitio aun
-- cuando posteriormente se edite la sede o la empresa.
ALTER TABLE fg_facturacion
    ADD COLUMN IF NOT EXISTS planta_key VARCHAR NULL,
    ADD COLUMN IF NOT EXISTS empresa_key VARCHAR NULL,
    ADD COLUMN IF NOT EXISTS ruc_emisor VARCHAR(11) NULL,
    ADD COLUMN IF NOT EXISTS razon_social_emisor VARCHAR(250) NULL,
    ADD COLUMN IF NOT EXISTS direccion_emisor VARCHAR(500) NULL,
    ADD COLUMN IF NOT EXISTS entorno_facturador VARCHAR(20) NULL,
    ADD COLUMN IF NOT EXISTS codigo_unico VARCHAR(20) NULL;

UPDATE fg_facturacion f
SET planta_key = COALESCE(f.planta_key, c.planta_key),
    empresa_key = COALESCE(f.empresa_key, p.empresa_key),
    ruc_emisor = COALESCE(f.ruc_emisor, e.ruc),
    razon_social_emisor = COALESCE(f.razon_social_emisor, e.nombre),
    direccion_emisor = COALESCE(f.direccion_emisor, e.direccion),
    entorno_facturador = COALESCE(f.entorno_facturador, 'DEMO'),
    codigo_unico = COALESCE(f.codigo_unico, 'FG-' || f.id::text)
FROM fg_certificado c
JOIN fg_planta p ON p.key = c.planta_key
JOIN fg_empresa e ON e.key = p.empresa_key
WHERE c.id = f.certificado_id
  AND (
      f.planta_key IS NULL OR f.empresa_key IS NULL OR f.ruc_emisor IS NULL
      OR f.razon_social_emisor IS NULL OR f.entorno_facturador IS NULL
      OR f.codigo_unico IS NULL
  );

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_fg_facturacion_planta'
          AND conrelid = 'fg_facturacion'::regclass
    ) THEN
        ALTER TABLE fg_facturacion
            ADD CONSTRAINT fk_fg_facturacion_planta
            FOREIGN KEY (planta_key) REFERENCES fg_planta(key)
            ON UPDATE CASCADE ON DELETE RESTRICT;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_fg_facturacion_empresa'
          AND conrelid = 'fg_facturacion'::regclass
    ) THEN
        ALTER TABLE fg_facturacion
            ADD CONSTRAINT fk_fg_facturacion_empresa
            FOREIGN KEY (empresa_key) REFERENCES fg_empresa(key)
            ON UPDATE CASCADE ON DELETE RESTRICT;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'ck_fg_facturacion_ruc_emisor'
          AND conrelid = 'fg_facturacion'::regclass
    ) THEN
        ALTER TABLE fg_facturacion
            ADD CONSTRAINT ck_fg_facturacion_ruc_emisor
            CHECK (ruc_emisor IS NULL OR ruc_emisor ~ '^[0-9]{11}$');
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'ck_fg_facturacion_entorno'
          AND conrelid = 'fg_facturacion'::regclass
    ) THEN
        ALTER TABLE fg_facturacion
            ADD CONSTRAINT ck_fg_facturacion_entorno
            CHECK (entorno_facturador IS NULL OR entorno_facturador IN ('DEMO', 'PRODUCCION'));
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'ck_fg_facturacion_codigo_unico'
          AND conrelid = 'fg_facturacion'::regclass
    ) THEN
        ALTER TABLE fg_facturacion
            ADD CONSTRAINT ck_fg_facturacion_codigo_unico
            CHECK (codigo_unico IS NULL OR (BTRIM(codigo_unico) <> '' AND CHAR_LENGTH(codigo_unico) <= 20));
    END IF;
END $$;

-- El numero debe ser unico dentro de la empresa emisora. Dos empresas legales
-- pueden utilizar la misma serie y el mismo numero sin colisionar entre ellas.
ALTER TABLE fg_facturacion
    DROP CONSTRAINT IF EXISTS uq_fg_facturacion_serie_numero;

CREATE UNIQUE INDEX IF NOT EXISTS uq_fg_facturacion_empresa_serie_numero
    ON fg_facturacion (empresa_key, serie, numero)
    WHERE empresa_key IS NOT NULL AND serie IS NOT NULL AND numero IS NOT NULL;

-- Idempotencia estable para reintentos y recuperacion por consulta.
CREATE UNIQUE INDEX IF NOT EXISTS uq_fg_facturacion_proveedor_codigo_unico
    ON fg_facturacion (proveedor, codigo_unico)
    WHERE codigo_unico IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_fg_facturacion_emisor
    ON fg_facturacion (empresa_key, entorno_facturador, fecha_creacion DESC);

COMMENT ON COLUMN fg_empresa_facturador.credencial_clave IS
    'Identificador de variables de entorno; nunca contiene ruta ni token.';
COMMENT ON COLUMN fg_facturacion.codigo_unico IS
    'Idempotencia Nubefact estable para todos los reintentos de una facturacion.';

COMMIT;
