BEGIN;

CREATE TABLE IF NOT EXISTS fg_facturacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    certificado_id BIGINT NOT NULL UNIQUE,
    tipo_comprobante VARCHAR(10) NOT NULL,
    tipo_documento_cliente VARCHAR(3) NOT NULL,
    nro_documento VARCHAR(15) NOT NULL,
    nombre_razon_social VARCHAR(250) NOT NULL,
    direccion VARCHAR(500) NOT NULL,
    email VARCHAR(150),
    telefono VARCHAR(30),
    moneda_key VARCHAR(20) NOT NULL DEFAULT 'sol',
    base_imponible NUMERIC(14, 2) NOT NULL,
    igv NUMERIC(14, 2) NOT NULL,
    importe_total NUMERIC(14, 2) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'BORRADOR',
    serie VARCHAR(20),
    numero BIGINT,
    nro_comprobante VARCHAR(50),
    proveedor VARCHAR(30) NOT NULL DEFAULT 'NUBEFACT',
    aceptada_sunat BOOLEAN,
    sunat_description TEXT,
    sunat_responsecode VARCHAR(50),
    sunat_soap_error TEXT,
    enlace_pdf TEXT,
    enlace_xml TEXT,
    enlace_cdr TEXT,
    cadena_qr TEXT,
    codigo_hash TEXT,
    respuesta_proveedor JSONB,
    intentos INTEGER NOT NULL DEFAULT 0,
    fecha_ultimo_intento TIMESTAMP,
    fecha_aceptacion TIMESTAMP,
    usuario_creacion VARCHAR(255) NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usuario_modificacion VARCHAR(255),
    fecha_modificacion TIMESTAMP,
    CONSTRAINT fk_fg_facturacion_certificado
        FOREIGN KEY (certificado_id)
        REFERENCES fg_certificado (id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_fg_facturacion_moneda
        FOREIGN KEY (moneda_key)
        REFERENCES moneda (key) ON UPDATE CASCADE,
    CONSTRAINT ck_fg_facturacion_tipo
        CHECK (tipo_comprobante IN ('BOLETA', 'FACTURA')),
    CONSTRAINT ck_fg_facturacion_documento
        CHECK (tipo_documento_cliente IN ('DNI', 'RUC')),
    CONSTRAINT ck_fg_facturacion_estado
        CHECK (estado IN ('BORRADOR', 'PENDIENTE', 'ACEPTADO', 'RECHAZADO', 'ERROR')),
    CONSTRAINT ck_fg_facturacion_importes
        CHECK (base_imponible >= 0 AND igv >= 0 AND importe_total >= 0),
    CONSTRAINT uq_fg_facturacion_serie_numero
        UNIQUE (serie, numero)
);

CREATE TABLE IF NOT EXISTS fg_facturacion_intento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facturacion_id BIGINT NOT NULL,
    numero_intento INTEGER NOT NULL,
    estado VARCHAR(20) NOT NULL,
    solicitud JSONB NOT NULL,
    respuesta JSONB,
    http_status INTEGER,
    error TEXT,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_finalizacion TIMESTAMP,
    CONSTRAINT fk_fg_facturacion_intento_facturacion
        FOREIGN KEY (facturacion_id)
        REFERENCES fg_facturacion (id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT ck_fg_facturacion_intento_estado
        CHECK (estado IN ('PENDIENTE', 'ACEPTADO', 'RECHAZADO', 'ERROR')),
    CONSTRAINT uq_fg_facturacion_intento_numero
        UNIQUE (facturacion_id, numero_intento)
);

CREATE INDEX IF NOT EXISTS idx_fg_facturacion_estado
    ON fg_facturacion (estado);

CREATE INDEX IF NOT EXISTS idx_fg_facturacion_intento_facturacion
    ON fg_facturacion_intento (facturacion_id, numero_intento DESC);

COMMIT;
