BEGIN;

CREATE TABLE IF NOT EXISTS fg_serie_comprobante (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    planta_key VARCHAR(50) NOT NULL,
    tipo_comprobante VARCHAR(30) NOT NULL,
    serie VARCHAR(30) NOT NULL,
    ultimo_numero BIGINT NOT NULL DEFAULT 0,
    es_predeterminada BOOLEAN NOT NULL DEFAULT FALSE,
    autogenerada BOOLEAN NOT NULL DEFAULT TRUE,
    contingencia BOOLEAN NOT NULL DEFAULT FALSE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT fk_fg_serie_comprobante_planta
        FOREIGN KEY (planta_key) REFERENCES fg_planta(key)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uk_fg_serie_comprobante_sede_tipo_serie
        UNIQUE (planta_key, tipo_comprobante, serie),
    CONSTRAINT chk_fg_serie_comprobante_tipo
        CHECK (tipo_comprobante IN ('FACTURA', 'BOLETA')),
    CONSTRAINT chk_fg_serie_comprobante_serie
        CHECK (btrim(serie) <> ''),
    CONSTRAINT chk_fg_serie_comprobante_numero
        CHECK (ultimo_numero >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_fg_serie_comprobante_predeterminada_activa
    ON fg_serie_comprobante (planta_key, tipo_comprobante)
    WHERE activo = TRUE AND es_predeterminada = TRUE;

CREATE INDEX IF NOT EXISTS idx_fg_serie_comprobante_listado
    ON fg_serie_comprobante (planta_key, tipo_comprobante, activo);

-- Mapping controlado: la auditoría comprobó exactamente una fila legacy activa
-- por planta. Solo se copian los tipos que Faregas utiliza hoy: FACTURA y BOLETA.
INSERT INTO fg_serie_comprobante (
    planta_key, tipo_comprobante, serie, ultimo_numero,
    es_predeterminada, autogenerada, contingencia, activo
)
SELECT s.planta_key, 'FACTURA', btrim(s.seriefactura), s.nroactualfactura,
       TRUE, TRUE, FALSE, TRUE
FROM seriedocumentobase s
JOIN fg_planta p ON p.key = s.planta_key
WHERE COALESCE(s.estado, TRUE) = TRUE
  AND btrim(s.seriefactura) <> ''
  AND NOT EXISTS (
      SELECT 1 FROM seriedocumentobase otra
      WHERE otra.planta_key = s.planta_key
        AND COALESCE(otra.estado, TRUE) = TRUE
        AND otra.id <> s.id
  )
ON CONFLICT (planta_key, tipo_comprobante, serie) DO NOTHING;

INSERT INTO fg_serie_comprobante (
    planta_key, tipo_comprobante, serie, ultimo_numero,
    es_predeterminada, autogenerada, contingencia, activo
)
SELECT s.planta_key, 'BOLETA', btrim(s.serieboleta), s.nroactualboleta,
       TRUE, TRUE, FALSE, TRUE
FROM seriedocumentobase s
JOIN fg_planta p ON p.key = s.planta_key
WHERE COALESCE(s.estado, TRUE) = TRUE
  AND btrim(s.serieboleta) <> ''
  AND NOT EXISTS (
      SELECT 1 FROM seriedocumentobase otra
      WHERE otra.planta_key = s.planta_key
        AND COALESCE(otra.estado, TRUE) = TRUE
        AND otra.id <> s.id
  )
ON CONFLICT (planta_key, tipo_comprobante, serie) DO NOTHING;

INSERT INTO fg_permiso (clave, nombre, modulo, descripcion, activo)
VALUES (
    'CONFIGURACION_SERIES',
    'Administrar Series de Comprobante',
    'FAREGAS',
    'Administrar series propias de comprobantes Faregas por sede',
    TRUE
)
ON CONFLICT (clave) DO NOTHING;

INSERT INTO fg_perfil_permiso (perfil_clave, permiso_clave)
SELECT 'SISTEMAS', 'CONFIGURACION_SERIES'
WHERE EXISTS (SELECT 1 FROM fg_perfil WHERE clave = 'SISTEMAS')
ON CONFLICT DO NOTHING;

COMMIT;
