BEGIN;

CREATE TABLE IF NOT EXISTS fg_inventario_cantidad_movimiento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_inventariable_id BIGINT NOT NULL
        REFERENCES fg_producto_inventariable(id) ON DELETE RESTRICT,
    planta_key VARCHAR NOT NULL
        REFERENCES fg_planta(key) ON DELETE RESTRICT,
    tipo_movimiento VARCHAR(20) NOT NULL
        CHECK (tipo_movimiento IN ('INGRESO', 'VENTA', 'AJUSTE', 'DEVOLUCION')),
    sentido VARCHAR(10) NOT NULL
        CHECK (sentido IN ('ENTRADA', 'SALIDA')),
    cantidad NUMERIC(12,3) NOT NULL CHECK (cantidad > 0),
    operacion_detalle_id BIGINT NULL
        REFERENCES fg_operacion_detalle(id) ON DELETE RESTRICT,
    usuario VARCHAR NOT NULL REFERENCES usuario(username) ON DELETE RESTRICT,
    referencia VARCHAR(250) NULL,
    detalles JSONB NOT NULL DEFAULT '{}'::jsonb,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fg_inventario_cantidad_movimiento_tipo_sentido_ck CHECK (
        (tipo_movimiento IN ('INGRESO', 'DEVOLUCION') AND sentido = 'ENTRADA')
        OR (tipo_movimiento = 'VENTA' AND sentido = 'SALIDA')
        OR tipo_movimiento = 'AJUSTE'
    ),
    CONSTRAINT fg_inventario_cantidad_movimiento_venta_uk UNIQUE (operacion_detalle_id)
);

CREATE INDEX IF NOT EXISTS fg_inventario_cantidad_movimiento_stock_idx
    ON fg_inventario_cantidad_movimiento
       (producto_inventariable_id, planta_key, fecha_creacion, id);

CREATE INDEX IF NOT EXISTS fg_inventario_cantidad_movimiento_operacion_idx
    ON fg_inventario_cantidad_movimiento (operacion_detalle_id)
    WHERE operacion_detalle_id IS NOT NULL;

CREATE OR REPLACE FUNCTION fg_bloquear_mutacion_movimiento_inventario_cantidad()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'Los movimientos de inventario por cantidad son inmutables';
END;
$$;

DROP TRIGGER IF EXISTS fg_inventario_cantidad_movimiento_inmutable
    ON fg_inventario_cantidad_movimiento;
CREATE TRIGGER fg_inventario_cantidad_movimiento_inmutable
BEFORE UPDATE OR DELETE ON fg_inventario_cantidad_movimiento
FOR EACH ROW EXECUTE FUNCTION fg_bloquear_mutacion_movimiento_inventario_cantidad();

DO $$
DECLARE
    v_surco_nombre TEXT;
    v_glp_id BIGINT;
    v_conformidad_id BIGINT;
    v_hoja_glp_id BIGINT;
    v_hoja_conformidad_id BIGINT;
BEGIN
    SELECT nombre INTO v_surco_nombre
      FROM fg_planta
     WHERE key = '98' AND activo = TRUE;
    IF v_surco_nombre IS NULL OR UPPER(TRIM(v_surco_nombre)) <> 'SURCO' THEN
        RAISE EXCEPTION 'No se confirmó SURCO activo con planta_key=98';
    END IF;

    SELECT id INTO v_glp_id
      FROM fg_producto_facturacion
     WHERE codigo_sku = '0130'
       AND UPPER(descripcion) = 'CERTIFICADO GLP'
       AND activo = TRUE
       AND es_para_venta = TRUE
       AND precio_referencia = 30.00;
    IF v_glp_id IS NULL THEN
        RAISE EXCEPTION 'No coincide el producto fiscal SKU 0130 / CERTIFICADO GLP / P. venta 30.00';
    END IF;

    SELECT id INTO v_conformidad_id
      FROM fg_producto_facturacion
     WHERE codigo_sku = '0132'
       AND UPPER(descripcion) = 'CERTIFICADO CONFORMIDAD'
       AND activo = TRUE
       AND es_para_venta = TRUE
       AND precio_referencia = 30.00;
    IF v_conformidad_id IS NULL THEN
        RAISE EXCEPTION 'No coincide el producto fiscal SKU 0132 / CERTIFICADO CONFORMIDAD / P. venta 30.00';
    END IF;

    INSERT INTO fg_producto_inventariable
        (codigo, nombre, tipo, producto_facturacion_id, control_stock, activo)
    VALUES
        ('HOJA_GLP', 'Certificado GLP - Hojas', 'CANTIDAD', NULL, TRUE, TRUE)
    ON CONFLICT (codigo) DO UPDATE
       SET nombre = EXCLUDED.nombre,
           tipo = EXCLUDED.tipo,
           control_stock = TRUE,
           activo = TRUE,
           fecha_modificacion = CURRENT_TIMESTAMP
    RETURNING id INTO v_hoja_glp_id;

    INSERT INTO fg_producto_inventariable
        (codigo, nombre, tipo, producto_facturacion_id, control_stock, activo)
    VALUES
        ('HOJA_CONFORMIDAD', 'Certificado Conformidad - Hojas', 'CANTIDAD', NULL, TRUE, TRUE)
    ON CONFLICT (codigo) DO UPDATE
       SET nombre = EXCLUDED.nombre,
           tipo = EXCLUDED.tipo,
           control_stock = TRUE,
           activo = TRUE,
           fecha_modificacion = CURRENT_TIMESTAMP
    RETURNING id INTO v_hoja_conformidad_id;

    INSERT INTO fg_producto_inventariable_sede
        (producto_inventariable_id, planta_key, precio, activo,
         stock_permitido, venta_habilitada, producto_facturacion_id)
    VALUES
        (v_hoja_glp_id, '98', 30.00, TRUE, TRUE, TRUE, v_glp_id),
        (v_hoja_conformidad_id, '98', 30.00, TRUE, TRUE, TRUE, v_conformidad_id)
    ON CONFLICT (producto_inventariable_id, planta_key) DO UPDATE
       SET activo = TRUE,
           stock_permitido = TRUE,
           venta_habilitada = TRUE,
           producto_facturacion_id = EXCLUDED.producto_facturacion_id,
           fecha_modificacion = CURRENT_TIMESTAMP;

    IF EXISTS (
        SELECT 1
          FROM fg_producto_inventariable_sede pis
          JOIN fg_producto_inventariable pi ON pi.id = pis.producto_inventariable_id
         WHERE pi.codigo IN ('HOJA_GLP', 'HOJA_CONFORMIDAD')
           AND pis.activo = TRUE
           AND pis.planta_key <> '98'
    ) THEN
        RAISE EXCEPTION 'Las hojas tienen una configuración activa fuera de SURCO';
    END IF;
END;
$$;

COMMIT;
