BEGIN;

-- Complemento del facturador FAREGAS. No contiene credenciales y no emite
-- documentos: solo prepara persistencia transaccional y trazabilidad.
ALTER TABLE fg_facturacion
    ADD COLUMN IF NOT EXISTS condicion_pago VARCHAR(10) NOT NULL DEFAULT 'CONTADO',
    ADD COLUMN IF NOT EXISTS fecha_vencimiento DATE NULL,
    ADD COLUMN IF NOT EXISTS medio_pago VARCHAR(250) NULL;

ALTER TABLE fg_facturacion
    DROP CONSTRAINT IF EXISTS ck_fg_facturacion_estado;
ALTER TABLE fg_facturacion
    ADD CONSTRAINT ck_fg_facturacion_estado
    CHECK (estado IN ('BORRADOR', 'PENDIENTE', 'ACEPTADO', 'RECHAZADO', 'ERROR', 'ANULADO'));

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'ck_fg_facturacion_condicion_pago'
          AND conrelid = 'fg_facturacion'::regclass
    ) THEN
        ALTER TABLE fg_facturacion
            ADD CONSTRAINT ck_fg_facturacion_condicion_pago
            CHECK (condicion_pago IN ('CONTADO', 'CREDITO'));
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS fg_facturacion_cuota (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facturacion_id BIGINT NOT NULL,
    numero_cuota INTEGER NOT NULL,
    fecha_pago DATE NOT NULL,
    importe NUMERIC(14,2) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    fecha_creacion TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion TIMESTAMP WITHOUT TIME ZONE NULL,
    CONSTRAINT fk_fg_facturacion_cuota_facturacion
        FOREIGN KEY (facturacion_id) REFERENCES fg_facturacion(id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT uq_fg_facturacion_cuota_numero
        UNIQUE (facturacion_id, numero_cuota),
    CONSTRAINT ck_fg_facturacion_cuota_numero CHECK (numero_cuota > 0),
    CONSTRAINT ck_fg_facturacion_cuota_importe CHECK (importe > 0),
    CONSTRAINT ck_fg_facturacion_cuota_estado
        CHECK (estado IN ('PENDIENTE', 'PAGADA', 'ANULADA'))
);

CREATE INDEX IF NOT EXISTS ix_fg_facturacion_cuota_vencimiento
    ON fg_facturacion_cuota (facturacion_id, fecha_pago, numero_cuota);

-- Completa los datos de respuesta de las notas existentes. Las tablas
-- fg_credito y fg_debito ya existían y se conservan.
ALTER TABLE fg_credito
    ADD COLUMN IF NOT EXISTS empresa_key VARCHAR NULL,
    ADD COLUMN IF NOT EXISTS ruc_emisor VARCHAR(11) NULL,
    ADD COLUMN IF NOT EXISTS codigo_unico VARCHAR(20) NULL,
    ADD COLUMN IF NOT EXISTS sunat_description TEXT NULL,
    ADD COLUMN IF NOT EXISTS sunat_responsecode VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS sunat_soap_error TEXT NULL,
    ADD COLUMN IF NOT EXISTS enlace_pdf TEXT NULL,
    ADD COLUMN IF NOT EXISTS enlace_xml TEXT NULL,
    ADD COLUMN IF NOT EXISTS enlace_cdr TEXT NULL,
    ADD COLUMN IF NOT EXISTS intentos INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS fecha_ultimo_intento TIMESTAMP WITHOUT TIME ZONE NULL,
    ADD COLUMN IF NOT EXISTS fecha_aceptacion TIMESTAMP WITHOUT TIME ZONE NULL;

ALTER TABLE fg_debito
    ADD COLUMN IF NOT EXISTS empresa_key VARCHAR NULL,
    ADD COLUMN IF NOT EXISTS ruc_emisor VARCHAR(11) NULL,
    ADD COLUMN IF NOT EXISTS codigo_unico VARCHAR(20) NULL,
    ADD COLUMN IF NOT EXISTS sunat_description TEXT NULL,
    ADD COLUMN IF NOT EXISTS sunat_responsecode VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS sunat_soap_error TEXT NULL,
    ADD COLUMN IF NOT EXISTS enlace_pdf TEXT NULL,
    ADD COLUMN IF NOT EXISTS enlace_xml TEXT NULL,
    ADD COLUMN IF NOT EXISTS enlace_cdr TEXT NULL,
    ADD COLUMN IF NOT EXISTS intentos INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS fecha_ultimo_intento TIMESTAMP WITHOUT TIME ZONE NULL,
    ADD COLUMN IF NOT EXISTS fecha_aceptacion TIMESTAMP WITHOUT TIME ZONE NULL;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_fg_credito_empresa') THEN
        ALTER TABLE fg_credito ADD CONSTRAINT fk_fg_credito_empresa
            FOREIGN KEY (empresa_key) REFERENCES fg_empresa(key)
            ON UPDATE CASCADE ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_fg_debito_empresa') THEN
        ALTER TABLE fg_debito ADD CONSTRAINT fk_fg_debito_empresa
            FOREIGN KEY (empresa_key) REFERENCES fg_empresa(key)
            ON UPDATE CASCADE ON DELETE RESTRICT;
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_fg_credito_proveedor_codigo_unico
    ON fg_credito (proveedor, codigo_unico) WHERE codigo_unico IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_fg_debito_proveedor_codigo_unico
    ON fg_debito (proveedor, codigo_unico) WHERE codigo_unico IS NOT NULL;

CREATE TABLE IF NOT EXISTS fg_documento_anulacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facturacion_id BIGINT NULL,
    credito_id BIGINT NULL,
    debito_id BIGINT NULL,
    motivo VARCHAR(100) NOT NULL,
    codigo_unico VARCHAR(20) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'BORRADOR',
    ticket_sunat VARCHAR(250) NULL,
    aceptada_sunat BOOLEAN NULL,
    sunat_description TEXT NULL,
    sunat_responsecode VARCHAR(50) NULL,
    sunat_soap_error TEXT NULL,
    enlace_pdf TEXT NULL,
    enlace_xml TEXT NULL,
    enlace_cdr TEXT NULL,
    respuesta_proveedor JSONB NULL,
    intentos INTEGER NOT NULL DEFAULT 0,
    fecha_ultimo_intento TIMESTAMP WITHOUT TIME ZONE NULL,
    fecha_aceptacion TIMESTAMP WITHOUT TIME ZONE NULL,
    usuario_creacion VARCHAR(255) NOT NULL,
    fecha_creacion TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usuario_modificacion VARCHAR(255) NULL,
    fecha_modificacion TIMESTAMP WITHOUT TIME ZONE NULL,
    CONSTRAINT fk_fg_anulacion_facturacion FOREIGN KEY (facturacion_id)
        REFERENCES fg_facturacion(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_fg_anulacion_credito FOREIGN KEY (credito_id)
        REFERENCES fg_credito(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_fg_anulacion_debito FOREIGN KEY (debito_id)
        REFERENCES fg_debito(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_fg_anulacion_usuario_creacion FOREIGN KEY (usuario_creacion)
        REFERENCES fg_usuario(username) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_fg_anulacion_usuario_modificacion FOREIGN KEY (usuario_modificacion)
        REFERENCES fg_usuario(username) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT ck_fg_anulacion_documento CHECK (
        num_nonnulls(facturacion_id, credito_id, debito_id) = 1
    ),
    CONSTRAINT ck_fg_anulacion_estado CHECK (
        estado IN ('BORRADOR', 'PENDIENTE', 'ACEPTADO', 'RECHAZADO', 'ERROR')
    ),
    CONSTRAINT ck_fg_anulacion_motivo CHECK (BTRIM(motivo) <> ''),
    CONSTRAINT ck_fg_anulacion_codigo CHECK (
        BTRIM(codigo_unico) <> '' AND CHAR_LENGTH(codigo_unico) <= 20
    ),
    CONSTRAINT uq_fg_anulacion_codigo UNIQUE (codigo_unico)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_fg_anulacion_facturacion_activa
    ON fg_documento_anulacion (facturacion_id)
    WHERE facturacion_id IS NOT NULL AND estado IN ('BORRADOR', 'PENDIENTE', 'ACEPTADO');
CREATE UNIQUE INDEX IF NOT EXISTS uq_fg_anulacion_credito_activa
    ON fg_documento_anulacion (credito_id)
    WHERE credito_id IS NOT NULL AND estado IN ('BORRADOR', 'PENDIENTE', 'ACEPTADO');
CREATE UNIQUE INDEX IF NOT EXISTS uq_fg_anulacion_debito_activa
    ON fg_documento_anulacion (debito_id)
    WHERE debito_id IS NOT NULL AND estado IN ('BORRADOR', 'PENDIENTE', 'ACEPTADO');

CREATE TABLE IF NOT EXISTS fg_documento_electronico_operacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facturacion_id BIGINT NULL,
    credito_id BIGINT NULL,
    debito_id BIGINT NULL,
    anulacion_id BIGINT NULL,
    operacion VARCHAR(30) NOT NULL,
    numero_intento INTEGER NOT NULL,
    estado VARCHAR(20) NOT NULL,
    solicitud JSONB NOT NULL,
    respuesta JSONB NULL,
    http_status INTEGER NULL,
    error TEXT NULL,
    usuario_creacion VARCHAR(255) NOT NULL,
    fecha_creacion TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_finalizacion TIMESTAMP WITHOUT TIME ZONE NULL,
    CONSTRAINT fk_fg_doc_operacion_facturacion FOREIGN KEY (facturacion_id)
        REFERENCES fg_facturacion(id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_fg_doc_operacion_credito FOREIGN KEY (credito_id)
        REFERENCES fg_credito(id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_fg_doc_operacion_debito FOREIGN KEY (debito_id)
        REFERENCES fg_debito(id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_fg_doc_operacion_anulacion FOREIGN KEY (anulacion_id)
        REFERENCES fg_documento_anulacion(id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_fg_doc_operacion_usuario FOREIGN KEY (usuario_creacion)
        REFERENCES fg_usuario(username) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT ck_fg_doc_operacion_documento CHECK (
        num_nonnulls(facturacion_id, credito_id, debito_id, anulacion_id) = 1
    ),
    CONSTRAINT ck_fg_doc_operacion_tipo CHECK (
        operacion IN ('EMITIR', 'CONSULTAR', 'ANULAR', 'CONSULTAR_ANULACION')
    ),
    CONSTRAINT ck_fg_doc_operacion_estado CHECK (
        estado IN ('PENDIENTE', 'ACEPTADO', 'PROCESANDO', 'RECHAZADO', 'ERROR')
    ),
    CONSTRAINT ck_fg_doc_operacion_intento CHECK (numero_intento > 0)
);

CREATE INDEX IF NOT EXISTS ix_fg_doc_operacion_facturacion
    ON fg_documento_electronico_operacion (facturacion_id, fecha_creacion DESC);
CREATE INDEX IF NOT EXISTS ix_fg_doc_operacion_credito
    ON fg_documento_electronico_operacion (credito_id, fecha_creacion DESC);
CREATE INDEX IF NOT EXISTS ix_fg_doc_operacion_debito
    ON fg_documento_electronico_operacion (debito_id, fecha_creacion DESC);
CREATE INDEX IF NOT EXISTS ix_fg_doc_operacion_anulacion
    ON fg_documento_electronico_operacion (anulacion_id, fecha_creacion DESC);

COMMIT;
