BEGIN;

CREATE TABLE IF NOT EXISTS fg_vehiculo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa VARCHAR(255) NOT NULL,
    placa_normalizada VARCHAR(255)
        GENERATED ALWAYS AS (UPPER(BTRIM(placa))) STORED,
    categoria VARCHAR(255),
    clase VARCHAR(255),
    marca VARCHAR(255),
    modelo VARCHAR(255),
    version VARCHAR(255),
    anio_fabricacion VARCHAR(10),
    anio_modelo VARCHAR(10),
    vin VARCHAR(255),
    serie_chasis VARCHAR(255),
    numero_motor VARCHAR(255),
    combustible VARCHAR(255),
    color VARCHAR(255),
    carroceria VARCHAR(255),
    numero_cilindros INTEGER,
    cilindrada NUMERIC(10, 3),
    numero_ejes INTEGER,
    numero_ruedas INTEGER,
    numero_asientos INTEGER,
    numero_pasajeros INTEGER,
    longitud NUMERIC(10, 3),
    ancho NUMERIC(10, 3),
    alto NUMERIC(10, 3),
    peso_neto NUMERIC(10, 3),
    peso_bruto NUMERIC(10, 3),
    carga_util NUMERIC(10, 3),
    potencia VARCHAR(100),
    formula_rodante VARCHAR(50),
    fuente_ultima VARCHAR(20) NOT NULL,
    certificado_origen_id BIGINT,
    confirmado BOOLEAN NOT NULL DEFAULT FALSE,
    usuario_creacion VARCHAR(255) NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usuario_modificacion VARCHAR(255),
    fecha_modificacion TIMESTAMP,
    CONSTRAINT uq_fg_vehiculo_placa_normalizada UNIQUE (placa_normalizada),
    CONSTRAINT ck_fg_vehiculo_placa_no_vacia CHECK (BTRIM(placa) <> ''),
    CONSTRAINT ck_fg_vehiculo_fuente CHECK (fuente_ultima IN ('FARENET', 'FAREGAS', 'MANUAL')),
    CONSTRAINT fk_fg_vehiculo_certificado_origen
        FOREIGN KEY (certificado_origen_id)
        REFERENCES fg_certificado (id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_fg_vehiculo_usuario_creacion
        FOREIGN KEY (usuario_creacion)
        REFERENCES fg_usuario (username) ON UPDATE CASCADE,
    CONSTRAINT fk_fg_vehiculo_usuario_modificacion
        FOREIGN KEY (usuario_modificacion)
        REFERENCES fg_usuario (username) ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_fg_vehiculo_vin
    ON fg_vehiculo (UPPER(vin))
    WHERE vin IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_fg_vehiculo_numero_motor
    ON fg_vehiculo (UPPER(numero_motor))
    WHERE numero_motor IS NOT NULL;

COMMIT;
