BEGIN;

CREATE TABLE IF NOT EXISTS fg_categoria_servicio (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    orden INTEGER NOT NULL DEFAULT 0,
    fecha_creacion TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT uk_fg_categoria_servicio_codigo UNIQUE (codigo)
);

INSERT INTO fg_categoria_servicio (codigo, nombre, descripcion, activo, orden)
VALUES
    ('GLP', 'GLP', 'Servicios relacionados con Gas Licuado de Petróleo.', TRUE, 10),
    ('GNV', 'GNV', 'Servicios relacionados con Gas Natural Vehicular.', TRUE, 20),
    ('CONFORMIDAD', 'Conformidad', 'Certificados de conformidad vehicular.', TRUE, 30),
    ('OTROS_CERTIFICADOS', 'Otros certificados', 'Otros servicios que generan certificados.', TRUE, 40),
    ('COMPLEMENTARIOS', 'Complementarios', 'Servicios complementarios que no pertenecen a las categorías principales.', TRUE, 50)
ON CONFLICT (codigo) DO NOTHING;

ALTER TABLE fg_servicio
    ADD COLUMN IF NOT EXISTS categoria_id INTEGER;

UPDATE fg_servicio s
SET categoria_id = c.id
FROM fg_categoria_servicio c
WHERE s.categoria_id IS NULL
  AND c.codigo = CASE
      WHEN s.codigo LIKE 'GLP_%' OR s.familia = 'GLP' THEN 'GLP'
      WHEN s.codigo LIKE 'GNV_%' OR s.familia = 'GNV' THEN 'GNV'
      WHEN s.codigo LIKE 'CONFORMIDAD_%' OR s.familia = 'CONFORMIDAD' THEN 'CONFORMIDAD'
      ELSE NULL
  END;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM fg_servicio WHERE categoria_id IS NULL) THEN
        RAISE EXCEPTION 'Existen servicios Faregas sin categoría; se cancela la migración.';
    END IF;
END $$;

ALTER TABLE fg_servicio
    ALTER COLUMN categoria_id SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_fg_servicio_categoria'
    ) THEN
        ALTER TABLE fg_servicio
            ADD CONSTRAINT fk_fg_servicio_categoria
            FOREIGN KEY (categoria_id)
            REFERENCES fg_categoria_servicio (id)
            ON UPDATE CASCADE ON DELETE RESTRICT;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_fg_servicio_categoria
    ON fg_servicio (categoria_id);

ALTER TABLE fg_tarifa
    ADD COLUMN IF NOT EXISTS servicio_id INTEGER;

UPDATE fg_tarifa t
SET servicio_id = s.id
FROM fg_servicio s
WHERE t.servicio_id IS NULL
  AND t.codigo = s.codigo;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM fg_tarifa WHERE servicio_id IS NULL) THEN
        RAISE EXCEPTION 'Existen tarifas Faregas sin servicio; se cancela la migración.';
    END IF;
END $$;

ALTER TABLE fg_tarifa
    ALTER COLUMN servicio_id SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_fg_tarifa_servicio'
    ) THEN
        ALTER TABLE fg_tarifa
            ADD CONSTRAINT fk_fg_tarifa_servicio
            FOREIGN KEY (servicio_id)
            REFERENCES fg_servicio (id)
            ON UPDATE CASCADE ON DELETE RESTRICT;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_fg_tarifa_servicio
    ON fg_tarifa (servicio_id);

CREATE UNIQUE INDEX IF NOT EXISTS uk_fg_tarifa_planta_servicio
    ON fg_tarifa (planta_key, servicio_id);

INSERT INTO fg_permiso (clave, nombre, modulo, descripcion, activo)
VALUES (
    'CONFIGURACION_CATEGORIAS',
    'Administrar Categorías',
    'FAREGAS',
    'Administrar categorías comerciales de servicios Faregas',
    TRUE
)
ON CONFLICT (clave) DO NOTHING;

-- SISTEMAS es el perfil técnico-administrador existente. No se concede el
-- permiso a otros perfiles de manera automática.
INSERT INTO fg_perfil_permiso (perfil_clave, permiso_clave)
SELECT 'SISTEMAS', 'CONFIGURACION_CATEGORIAS'
WHERE EXISTS (SELECT 1 FROM fg_perfil WHERE clave = 'SISTEMAS')
ON CONFLICT DO NOTHING;

COMMIT;
