BEGIN;

CREATE TABLE IF NOT EXISTS fg_producto_inventariable (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(60) NOT NULL UNIQUE,
    nombre VARCHAR(200) NOT NULL,
    producto_facturacion_id BIGINT NULL REFERENCES fg_producto_facturacion(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    control_stock BOOLEAN NOT NULL DEFAULT TRUE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion TIMESTAMP WITHOUT TIME ZONE NULL,
    CONSTRAINT ck_fg_producto_inventariable_codigo CHECK (btrim(codigo) <> ''),
    CONSTRAINT ck_fg_producto_inventariable_nombre CHECK (btrim(nombre) <> '')
);

CREATE TABLE IF NOT EXISTS fg_producto_inventariable_sede (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_inventariable_id BIGINT NOT NULL REFERENCES fg_producto_inventariable(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    planta_key VARCHAR NOT NULL REFERENCES fg_planta(key) ON UPDATE CASCADE ON DELETE RESTRICT,
    precio NUMERIC(14,2) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion TIMESTAMP WITHOUT TIME ZONE NULL,
    CONSTRAINT uq_fg_producto_inventariable_sede UNIQUE (producto_inventariable_id, planta_key),
    CONSTRAINT ck_fg_producto_inventariable_sede_precio CHECK (precio > 0)
);

CREATE TABLE IF NOT EXISTS fg_chip (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_inventariable_id BIGINT NOT NULL REFERENCES fg_producto_inventariable(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    numero_chip VARCHAR(120) NOT NULL UNIQUE,
    planta_actual_key VARCHAR NOT NULL REFERENCES fg_planta(key) ON UPDATE CASCADE ON DELETE RESTRICT,
    estado VARCHAR(20) NOT NULL DEFAULT 'DISPONIBLE',
    operacion_reserva_id BIGINT NULL REFERENCES fg_operacion_comercial(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    reservado_en TIMESTAMP WITHOUT TIME ZONE NULL,
    creado_por VARCHAR NOT NULL REFERENCES fg_usuario(username) ON UPDATE CASCADE ON DELETE RESTRICT,
    creado_en TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por VARCHAR NULL REFERENCES fg_usuario(username) ON UPDATE CASCADE ON DELETE RESTRICT,
    actualizado_en TIMESTAMP WITHOUT TIME ZONE NULL,
    CONSTRAINT ck_fg_chip_numero CHECK (btrim(numero_chip) <> ''),
    CONSTRAINT ck_fg_chip_estado CHECK (estado IN ('DISPONIBLE','RESERVADO','VENDIDO','BAJA')),
    CONSTRAINT ck_fg_chip_reserva CHECK (
        (estado = 'RESERVADO' AND operacion_reserva_id IS NOT NULL AND reservado_en IS NOT NULL)
        OR (estado <> 'RESERVADO' AND operacion_reserva_id IS NULL AND reservado_en IS NULL)
    )
);

CREATE INDEX IF NOT EXISTS ix_fg_chip_stock ON fg_chip(planta_actual_key, estado, producto_inventariable_id);

CREATE TABLE IF NOT EXISTS fg_chip_movimiento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chip_id BIGINT NOT NULL REFERENCES fg_chip(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    tipo_movimiento VARCHAR(20) NOT NULL,
    planta_origen_key VARCHAR NULL REFERENCES fg_planta(key) ON UPDATE CASCADE ON DELETE RESTRICT,
    planta_destino_key VARCHAR NULL REFERENCES fg_planta(key) ON UPDATE CASCADE ON DELETE RESTRICT,
    usuario VARCHAR NOT NULL REFERENCES fg_usuario(username) ON UPDATE CASCADE ON DELETE RESTRICT,
    fecha TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    referencia VARCHAR(200) NULL,
    certificado_id BIGINT NULL REFERENCES fg_certificado(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    operacion_comercial_id BIGINT NULL REFERENCES fg_operacion_comercial(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    detalles JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT ck_fg_chip_movimiento_tipo CHECK (tipo_movimiento IN ('INGRESO','TRANSFERENCIA','RESERVA','LIBERACION','VENTA','AJUSTE','BAJA'))
);

CREATE INDEX IF NOT EXISTS ix_fg_chip_movimiento_chip ON fg_chip_movimiento(chip_id, fecha DESC, id DESC);

CREATE TABLE IF NOT EXISTS fg_certificado_chip (
    certificado_id BIGINT NOT NULL REFERENCES fg_certificado(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    chip_id BIGINT NOT NULL REFERENCES fg_chip(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    fecha_asociacion TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (certificado_id, chip_id),
    CONSTRAINT uq_fg_certificado_chip_chip UNIQUE (chip_id)
);

CREATE TABLE IF NOT EXISTS fg_operacion_detalle_chip (
    operacion_detalle_id BIGINT PRIMARY KEY REFERENCES fg_operacion_detalle(id) ON UPDATE CASCADE ON DELETE CASCADE,
    chip_id BIGINT NOT NULL UNIQUE REFERENCES fg_chip(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

INSERT INTO fg_producto_inventariable (codigo, nombre, producto_facturacion_id, control_stock, activo)
VALUES ('CHIP', 'Chip y porta chip', NULL, TRUE, TRUE)
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO fg_producto_inventariable_sede (producto_inventariable_id, planta_key, precio, activo)
SELECT pi.id, p.key, 180, TRUE
FROM fg_producto_inventariable pi
JOIN fg_planta p ON p.empresa_key = 'FAREGAS' AND p.activo = TRUE
WHERE pi.codigo = 'CHIP'
ON CONFLICT (producto_inventariable_id, planta_key) DO UPDATE
SET precio = EXCLUDED.precio, activo = TRUE, fecha_modificacion = CURRENT_TIMESTAMP;

INSERT INTO fg_permiso (clave, nombre, modulo, descripcion, activo) VALUES
('CHIPS_VER', 'Ver inventario de chips', 'FAREGAS', 'Consultar stock e historial de chips', TRUE),
('CHIPS_INGRESAR', 'Ingresar chips', 'FAREGAS', 'Registrar chips físicos en una sede', TRUE),
('CHIPS_TRANSFERIR', 'Transferir chips', 'FAREGAS', 'Mover chips disponibles entre sedes', TRUE),
('CHIPS_BAJA', 'Dar de baja chips', 'FAREGAS', 'Dar de baja chips disponibles', TRUE)
ON CONFLICT (clave) DO NOTHING;

INSERT INTO fg_perfil_permiso (perfil_clave, permiso_clave)
SELECT 'SISTEMAS', clave FROM fg_permiso
WHERE clave IN ('CHIPS_VER','CHIPS_INGRESAR','CHIPS_TRANSFERIR','CHIPS_BAJA')
  AND EXISTS (SELECT 1 FROM fg_perfil WHERE clave = 'SISTEMAS')
ON CONFLICT DO NOTHING;

-- Registro de prueba sin uso comercial: se conserva, pero deja de aparecer en flujos activos.
UPDATE fg_servicio
SET activo = FALSE
WHERE codigo = 'SSS'
  AND NOT EXISTS (SELECT 1 FROM fg_tarifa t WHERE t.servicio_id = fg_servicio.id AND t.activo = TRUE);

COMMIT;
