BEGIN;

CREATE TABLE IF NOT EXISTS fg_producto_facturacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_sku VARCHAR(120) NOT NULL,
    descripcion VARCHAR(300) NOT NULL,
    tipo_producto VARCHAR(50),
    categoria_dms VARCHAR(200),
    cuenta_por_cobrar VARCHAR(200),
    unidad VARCHAR(20),
    precio_unitario NUMERIC(14, 4),
    precio_referencia NUMERIC(14, 4),
    valor_referencial_unitario NUMERIC(14, 4),
    codigo_clasificacion_sunat VARCHAR(30),
    tipo_afectacion_igv VARCHAR(10),
    porcentaje_isc NUMERIC(8, 4),
    disponible_pos BOOLEAN NOT NULL DEFAULT FALSE,
    es_para_venta BOOLEAN NOT NULL DEFAULT TRUE,
    es_para_compra BOOLEAN NOT NULL DEFAULT FALSE,
    tiene_icbper BOOLEAN NOT NULL DEFAULT FALSE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT uk_fg_producto_facturacion_sku UNIQUE (codigo_sku),
    CONSTRAINT chk_fg_producto_facturacion_sku CHECK (btrim(codigo_sku) <> ''),
    CONSTRAINT chk_fg_producto_facturacion_descripcion CHECK (btrim(descripcion) <> ''),
    CONSTRAINT chk_fg_producto_facturacion_precio_unitario CHECK (precio_unitario IS NULL OR precio_unitario >= 0),
    CONSTRAINT chk_fg_producto_facturacion_precio_referencia CHECK (precio_referencia IS NULL OR precio_referencia >= 0),
    CONSTRAINT chk_fg_producto_facturacion_valor_referencial CHECK (valor_referencial_unitario IS NULL OR valor_referencial_unitario >= 0),
    CONSTRAINT chk_fg_producto_facturacion_porcentaje_isc CHECK (porcentaje_isc IS NULL OR porcentaje_isc >= 0),
    CONSTRAINT chk_fg_producto_facturacion_afectacion CHECK (
        tipo_afectacion_igv IS NULL OR tipo_afectacion_igv ~ '^[0-9]{2}$'
    )
);

CREATE INDEX IF NOT EXISTS idx_fg_producto_facturacion_descripcion
    ON fg_producto_facturacion (descripcion);

CREATE INDEX IF NOT EXISTS idx_fg_producto_facturacion_filtros
    ON fg_producto_facturacion (activo, es_para_venta, unidad);

INSERT INTO fg_permiso (clave, nombre, modulo, descripcion, activo)
VALUES (
    'CONFIGURACION_PRODUCTOS',
    'Administrar Productos / SKU',
    'FAREGAS',
    'Administrar catálogo de productos de facturación Faregas',
    TRUE
)
ON CONFLICT (clave) DO NOTHING;

-- Se concede únicamente al perfil técnico-administrador existente.
INSERT INTO fg_perfil_permiso (perfil_clave, permiso_clave)
SELECT 'SISTEMAS', 'CONFIGURACION_PRODUCTOS'
WHERE EXISTS (SELECT 1 FROM fg_perfil WHERE clave = 'SISTEMAS')
ON CONFLICT DO NOTHING;

COMMIT;
