BEGIN;

CREATE TABLE IF NOT EXISTS fg_orden_pago (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    certificado_id bigint NOT NULL,
    importe_total double precision NOT NULL,
    baseimponible double precision NOT NULL,
    igv double precision NOT NULL,
    importe_pagado double precision NOT NULL DEFAULT 0,
    saldo_pendiente double precision NOT NULL,
    moneda_key character varying(20) NOT NULL DEFAULT 'sol',
    formapago_key character varying(20) NOT NULL DEFAULT 'contado',
    estado character varying(255) NOT NULL DEFAULT 'PENDIENTE',
    fechacreacion timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fechmodi timestamp without time zone,
    usuariocreacion_username character varying(255) NOT NULL,
    usuariomodi_username character varying(255),
    CONSTRAINT uq_fg_orden_pago_certificado UNIQUE (certificado_id),
    CONSTRAINT fk_fg_orden_pago_certificado FOREIGN KEY (certificado_id)
        REFERENCES fg_certificado (id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_fg_orden_pago_moneda FOREIGN KEY (moneda_key)
        REFERENCES moneda (key) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_fg_orden_pago_formapago FOREIGN KEY (formapago_key)
        REFERENCES formapago (key) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_fg_orden_pago_total CHECK (importe_total > 0),
    CONSTRAINT chk_fg_orden_pago_importe_pagado CHECK (importe_pagado >= 0),
    CONSTRAINT chk_fg_orden_pago_saldo CHECK (saldo_pendiente >= 0),
    CONSTRAINT chk_fg_orden_pago_estado CHECK (estado IN ('PENDIENTE', 'PAGADO', 'ANULADO'))
);

-- Replica los campos operativos de la tabla legacy pago. La relación
-- comprobante_id se adapta a orden_pago_id porque el comprobante Nubefact
-- se incorporará en su propia fase.
CREATE TABLE IF NOT EXISTS fg_pago (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    baseimponible double precision,
    digitotarjeta character varying(4),
    estado character varying(255),
    fechacreacion timestamp without time zone,
    fechdeposito timestamp without time zone,
    igv double precision,
    importe double precision,
    nrooperacionbanco character varying(75),
    nrooperaciontarjeta character varying(75),
    sendedtooffisis boolean,
    orden_pago_id bigint,
    cuentacorriente_key character varying(20),
    entidadfinanciera_key character varying(20),
    moneda_key character varying(20),
    tarjeta_key character varying(20),
    tipocontado_key character varying(20),
    CONSTRAINT fk_fg_pago_orden FOREIGN KEY (orden_pago_id)
        REFERENCES fg_orden_pago (id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_fg_pago_cuenta FOREIGN KEY (cuentacorriente_key)
        REFERENCES cuentacorriente (key) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_fg_pago_entidad FOREIGN KEY (entidadfinanciera_key)
        REFERENCES entidadfinanciera (key) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_fg_pago_moneda FOREIGN KEY (moneda_key)
        REFERENCES moneda (key) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_fg_pago_tarjeta FOREIGN KEY (tarjeta_key)
        REFERENCES tarjeta (key) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_fg_pago_tipo_contado FOREIGN KEY (tipocontado_key)
        REFERENCES tipocontado (key) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_fg_pago_importe CHECK (importe > 0),
    CONSTRAINT chk_fg_pago_digitos CHECK (digitotarjeta IS NULL OR digitotarjeta ~ '^[0-9]{4}$')
);

CREATE INDEX IF NOT EXISTS idx_fg_pago_orden ON fg_pago (orden_pago_id);
CREATE INDEX IF NOT EXISTS idx_fg_pago_tipo ON fg_pago (tipocontado_key);
CREATE INDEX IF NOT EXISTS idx_fg_pago_fecha ON fg_pago (fechacreacion);

COMMIT;
