-- Migración para asignar permisos faltantes al perfil ADMINISTRADOR
-- Se utiliza ON CONFLICT DO NOTHING para asegurar idempotencia.
-- El perfil real en la base de datos es AMINISTRADOR.

BEGIN;

INSERT INTO fg_perfil_permiso (perfil_clave, permiso_clave)
VALUES 
-- CONFIGURACIÓN
('AMINISTRADOR', 'MENU_CONFIGURACION'),
('AMINISTRADOR', 'MENU_CONFIGURACION_SEDES'),
('AMINISTRADOR', 'MENU_CONFIGURACION_CATALOGO'),
('AMINISTRADOR', 'MENU_CONFIGURACION_TARIFAS'),
('AMINISTRADOR', 'MENU_CONFIGURACION_CORRELATIVOS'),
('AMINISTRADOR', 'MENU_CONFIGURACION_EMPRESAS'),
('AMINISTRADOR', 'CONFIGURACION_SEDES'),
('AMINISTRADOR', 'CONFIGURACION_SERVICIOS'),
('AMINISTRADOR', 'CONFIGURACION_TARIFAS'),
('AMINISTRADOR', 'CONFIGURACION_CATEGORIAS'),
('AMINISTRADOR', 'CONFIGURACION_PRODUCTOS'),
('AMINISTRADOR', 'CONFIGURACION_SERIES'),
('AMINISTRADOR', 'CONFIGURACION_EMPRESAS'),

-- CHIPS / INVENTARIO -> VENTAS
('AMINISTRADOR', 'MENU_CHIPS'),
('AMINISTRADOR', 'MENU_CHIPS_VENTAS'),
('AMINISTRADOR', 'CHIPS_VER'),
('AMINISTRADOR', 'CHIPS_VENDER'),

-- DESCUENTOS
('AMINISTRADOR', 'MENU_DESCUENTOS'),
('AMINISTRADOR', 'DESCUENTOS_ADMINISTRAR')

ON CONFLICT (perfil_clave, permiso_clave) DO NOTHING;

COMMIT;
