BEGIN;

CREATE TABLE IF NOT EXISTS fg_certificado_formato (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    motor VARCHAR(30) NOT NULL,
    es_protegido BOOLEAN DEFAULT FALSE,
    activo BOOLEAN DEFAULT TRUE,
    creado_en TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    formato_padre_id INTEGER NULL
);

ALTER TABLE fg_certificado_formato
    ADD COLUMN IF NOT EXISTS formato_padre_id INTEGER NULL;

CREATE TABLE IF NOT EXISTS fg_certificado_formato_version (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    formato_id INTEGER NOT NULL,
    version INTEGER NOT NULL,
    archivo_ruta VARCHAR(255) NULL,
    configuracion JSONB NULL,
    estado VARCHAR(20) NOT NULL,
    vigente_desde TIMESTAMP WITHOUT TIME ZONE NULL,
    creado_por INTEGER NULL,
    creado_en TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    motor VARCHAR(50) NULL
);

ALTER TABLE fg_certificado_formato_version
    ADD COLUMN IF NOT EXISTS motor VARCHAR(50) NULL;

ALTER TABLE fg_servicio
    ADD COLUMN IF NOT EXISTS formato_id INTEGER NULL;

ALTER TABLE fg_certificado
    ADD COLUMN IF NOT EXISTS formato_version_id INTEGER NULL,
    ADD COLUMN IF NOT EXISTS formato_datos_snapshot JSONB NULL;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fg_certificado_formato_codigo_key') THEN
        ALTER TABLE fg_certificado_formato
            ADD CONSTRAINT fg_certificado_formato_codigo_key UNIQUE (codigo);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fg_certificado_formato_motor_check') THEN
        ALTER TABLE fg_certificado_formato
            ADD CONSTRAINT fg_certificado_formato_motor_check
            CHECK (motor IN ('SISTEMA', 'DOCX_DINAMICO', 'HTML_DINAMICO'));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fg_certificado_formato_formato_padre_id_fkey') THEN
        ALTER TABLE fg_certificado_formato
            ADD CONSTRAINT fg_certificado_formato_formato_padre_id_fkey
            FOREIGN KEY (formato_padre_id) REFERENCES fg_certificado_formato(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fg_certificado_formato_version_formato_id_fkey') THEN
        ALTER TABLE fg_certificado_formato_version
            ADD CONSTRAINT fg_certificado_formato_version_formato_id_fkey
            FOREIGN KEY (formato_id) REFERENCES fg_certificado_formato(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fg_certificado_formato_version_formato_id_version_key') THEN
        ALTER TABLE fg_certificado_formato_version
            ADD CONSTRAINT fg_certificado_formato_version_formato_id_version_key
            UNIQUE (formato_id, version);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fg_certificado_formato_version_estado_check') THEN
        ALTER TABLE fg_certificado_formato_version
            ADD CONSTRAINT fg_certificado_formato_version_estado_check
            CHECK (estado IN ('BORRADOR', 'VIGENTE', 'RETIRADA'));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fg_servicio_formato_id_fkey') THEN
        ALTER TABLE fg_servicio
            ADD CONSTRAINT fg_servicio_formato_id_fkey
            FOREIGN KEY (formato_id) REFERENCES fg_certificado_formato(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fg_certificado_formato_version_id_fkey') THEN
        ALTER TABLE fg_certificado
            ADD CONSTRAINT fg_certificado_formato_version_id_fkey
            FOREIGN KEY (formato_version_id) REFERENCES fg_certificado_formato_version(id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_fg_servicio_formato_id
    ON fg_servicio(formato_id);

CREATE INDEX IF NOT EXISTS idx_fg_certificado_formato_version_formato_estado
    ON fg_certificado_formato_version(formato_id, estado);

CREATE INDEX IF NOT EXISTS idx_fg_certificado_formato_version_id
    ON fg_certificado(formato_version_id);

COMMIT;
